### ISSUE TITLE
add an unordered list to the Hello World page

### ISSUE THREAD

**Issue by drwhite729** [drwhite729/lamp#6]
An unordered list looks like this:

- item 1
- item 2
- item 3

**Comment by JoleyWhite** [comment]
Can all the markup for an unordered list be in the same paragraph as a line of plain text at the top, or does it have to be in its own separate paragraph?

**Comment by drwhite729** [comment]
Neither, actually.  A paragraph and a list are both blocks, and blocks should not be nested.  Headings (H1, H2, ...) are also blocks.

Inline elements can occur inside of blocks -- like B for bold, I for italic, A for anchor (a link), etc.

**Comment by JoleyWhite** [comment]
So the list has to be in its own separate block, with the text at the top inside paragraph tags. Are the ul and slash-ul tags enough to put the list in its own block, or do I have to partner them with the paragraph tags?

**Comment by drwhite729** [comment]
No, the UL tags are the block.
